#!/usr/bin/env bash
set -euo pipefail

# EDIT THESE BEFORE RUNNING
INPUT_CSV="data/my_bom_dpp.csv"
TARGET_COL="repairability_bin"
GROUP_COL="supplier_region"
OUT_DIR="outputs/day1"

python src/day1_profile_clean.py \
  --input-csv "$INPUT_CSV" \
  --output-dir "$OUT_DIR" \
  --drop-cols supplier_name,partner_internal_id \
  --hash-cols product_id,component_id \
  --target-col "$TARGET_COL" \
  --group-col "$GROUP_COL"

python src/day1_baseline_classification.py \
  --input-csv "$OUT_DIR/cleaned_modeling.csv" \
  --target-col "$TARGET_COL" \
  --group-col "$GROUP_COL" \
  --output-dir "$OUT_DIR"

python src/export_schema_md.py \
  --schema-csv "$OUT_DIR/schema_inferred.csv" \
  --profile-json "$OUT_DIR/profile_summary.json" \
  --out-md docs/schema_draft_autogenerated.md

echo "Day 1 finished. Check $OUT_DIR and docs/schema_draft_autogenerated.md"
